# Generated by Django 5.1 on 2025-01-28 07:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=30, verbose_name='عنوان تبلیغ')),
                ('exp', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('delay', models.CharField(max_length=10, verbose_name='لطفا تاخیر در نمایش را تغییر ندهید')),
                ('img', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان مقاله')),
                ('subject', models.CharField(max_length=10, verbose_name='موضوع مقاله')),
                ('keyword', models.CharField(max_length=10, verbose_name='کلید واژه مقاله')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری')),
                ('writer', models.CharField(max_length=30, verbose_name='نویسنده')),
                ('summary', models.CharField(max_length=100, verbose_name='چکیده')),
                ('description', models.TextField(verbose_name='متن مقاله')),
                ('img', models.ImageField(upload_to='photo', verbose_name='تصویر اصلی مقاله')),
                ('img1', models.ImageField(null=True, upload_to='photo', verbose_name=' تصویر نمایشی مقاله در خانه')),
                ('wimg', models.ImageField(upload_to='photo', verbose_name='تصویر نویسنده مقاله')),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(null=True, upload_to='photo', verbose_name='بنر 1')),
                ('img2', models.ImageField(null=True, upload_to='photo', verbose_name='بنر 2')),
                ('msg1', models.CharField(max_length=500, verbose_name='توضیحات بنر 1')),
                ('msg2', models.CharField(max_length=100, verbose_name='  خبر مشکی بنر 2')),
                ('msg3', models.CharField(max_length=100, verbose_name='  خبر آبی بنر 2')),
                ('msg4', models.CharField(max_length=500, verbose_name='توضیحات بنر 2')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(null=True, upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='commentblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('comment', models.TextField(verbose_name='نظر')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='تاریخ بارگذاری')),
                ('num', models.IntegerField(null=True, verbose_name='شماره مقاله')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('gender', models.CharField(choices=[('1', 'مرد'), ('2', 'زن')], default='انتخاب کنید...', max_length=30)),
                ('responsibility', models.CharField(default='کارشناس', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('start_day', models.DateField(auto_now=True)),
                ('username', models.SlugField(error_messages={'unique': 'این نام کاربری قبلا توسط شخص دیگیری انتخاب شده.'}, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(null=True, upload_to='photo', verbose_name='عکس پرسنلی')),
                ('theme', models.CharField(choices=[('bg-theme-blue', 'blue'), ('bg-theme-yellow', 'yellow'), ('bg-theme-orange', 'orange'), ('bg-theme-pink', 'pink')], default='انتخاب کنید...', max_length=30, null=True, verbose_name='تم رنگی')),
            ],
        ),
        migrations.CreateModel(
            name='fquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ ')),
                ('group', models.CharField(choices=[('1', 'مشکلات پرداخت'), ('2', 'تحویل سفارش'), ('3', ' عمومی')], default='انتخاب کنید...', max_length=30, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('call', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('open', models.CharField(max_length=100, verbose_name='روز و ساعات کاری')),
                ('img', models.ImageField(null=True, upload_to='photo', verbose_name='لوگو')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='نام')),
                ('lname', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, verbose_name='آدرس ایمیل')),
                ('call', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254)),
                ('comment', models.TextField(verbose_name='نظر')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری')),
                ('num', models.IntegerField(verbose_name='شماره محصول')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialnews', models.CharField(max_length=100, null=True, verbose_name='خبر متحرک بالای صفحه')),
                ('follower', models.CharField(max_length=10, verbose_name='تعداد دنبال کنندگان')),
                ('customer', models.IntegerField(verbose_name='تعداد مشتریان')),
                ('dailyparcel', models.IntegerField(verbose_name='تعداد سفارشات روزانه')),
                ('dailyview', models.IntegerField(verbose_name='تعداد بازدیدهای روزانه از سایت')),
                ('rising', models.CharField(max_length=10, verbose_name='درصد رشد در سال')),
                ('variety', models.IntegerField(verbose_name='تنوع محصولات')),
                ('service1', models.CharField(max_length=30, verbose_name='خدمت 1 صفحه درباره ما')),
                ('service1detail', models.CharField(max_length=200, verbose_name='جزئیات خدمت 1')),
                ('service2', models.CharField(max_length=30, verbose_name='خدمت 2 صفحه درباره ما')),
                ('service2detail', models.CharField(max_length=200, verbose_name='جزئیات خدمت 2')),
                ('service3', models.CharField(max_length=30, verbose_name='خدمت 3 صفحه درباره ما')),
                ('service3detail', models.CharField(max_length=200, verbose_name='جزئیات خدمت 3')),
                ('service4', models.CharField(max_length=30, verbose_name='خدمت 4 صفحه درباره ما')),
                ('service4detail', models.CharField(max_length=200, verbose_name='جزئیات خدمت 4')),
                ('boldtitle', models.CharField(max_length=200, verbose_name='عنوان درباره ما')),
                ('description', models.TextField(null=True, verbose_name='معرفی یولو صفحه درباره ما')),
                ('img', models.ImageField(null=True, upload_to='photo', verbose_name='تصویر یولو صفحه درباره ما')),
            ],
        ),
        migrations.CreateModel(
            name='topservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.CharField(max_length=20, verbose_name='آپشن بالا صفحه اصلی')),
                ('optd', models.CharField(max_length=50, verbose_name='جزئیات آپشن  بالا صفحه اصلی')),
                ('color', models.CharField(max_length=20, verbose_name='لطفا تم رنگی را تغییر ندهید')),
            ],
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تحویل گیرنده')),
                ('call', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('city', models.CharField(max_length=20, verbose_name=' استان')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('zip', models.CharField(max_length=20, verbose_name=' کدپستی')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('normal', 'عادی'), ('vip', 'ویژه')], default='normal', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='shop_prd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('preprice', models.IntegerField()),
                ('curprice', models.IntegerField()),
                ('description', models.CharField(max_length=100, verbose_name='شرح مختصر محصول')),
                ('details', models.TextField(null=True, verbose_name='شرح کامل محصول')),
                ('img', models.ImageField(upload_to='photo', verbose_name='تصویر اصلی ')),
                ('img1', models.ImageField(null=True, upload_to='photo', verbose_name='تصویر فرعی 1 ')),
                ('img2', models.ImageField(null=True, upload_to='photo', verbose_name='تصویر فرعی 2 ')),
                ('img3', models.ImageField(null=True, upload_to='photo', verbose_name='تصویر فرعی 3 ')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='yolo.category')),
            ],
        ),
    ]
