# Generated by Django 5.1 on 2025-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
