# Generated by Django 5.1 on 2025-02-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0004_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='هنوز وارد نشده'),
        ),
        migrations.AddField(
            model_name='user_address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
