# Generated by Django 5.1 on 2024-09-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_prd',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='yolo.category'),
        ),
    ]
