# Generated by Django 5.1 on 2025-02-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0005_remove_user_address_email_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
