# Generated by Django 5.1 on 2024-09-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0005_shop_prd_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kitchen_prd',
        ),
    ]
