# Generated by Django 5.1 on 2024-09-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0006_delete_kitchen_prd'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('responsibility', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('start_day', models.DateField()),
                ('username', models.SlugField()),
            ],
        ),
    ]
