# Generated by Django 5.1 on 2024-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0007_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
