# Generated by Django 5.1 on 2024-09-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0008_remove_employee_id_alter_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('1', 'مرد'), ('2', 'زن')], default='انتخاب کنید...', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='responsibility',
            field=models.CharField(default='کارشناس', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_day',
            field=models.DateField(auto_now=True),
        ),
    ]
