# Generated by Django 5.1 on 2024-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0009_employee_gender_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.IntegerField()),
                ('customer', models.IntegerField()),
                ('dailyparcel', models.IntegerField()),
                ('dailyview', models.IntegerField()),
                ('rising', models.IntegerField()),
                ('variety', models.IntegerField()),
                ('service1', models.CharField(max_length=30)),
                ('service1detail', models.CharField(max_length=200)),
                ('service2', models.CharField(max_length=30)),
                ('service2detail', models.CharField(max_length=200)),
                ('service3', models.CharField(max_length=30)),
                ('service3detail', models.CharField(max_length=200)),
                ('service4', models.CharField(max_length=30)),
                ('service4detail', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=20)),
                ('option1detail', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=20)),
                ('option2detail', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=20)),
                ('option3detail', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=20)),
                ('option4detail', models.CharField(max_length=50)),
                ('option5', models.CharField(max_length=20)),
                ('option5detail', models.CharField(max_length=50)),
                ('option6', models.CharField(max_length=20)),
                ('option6detail', models.CharField(max_length=50)),
                ('option7', models.CharField(max_length=20)),
                ('option7detail', models.CharField(max_length=50)),
                ('option8', models.CharField(max_length=20)),
                ('option8detail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل معتبر وارد کنید', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.SlugField(error_messages={'unique': 'این نام کاربری قبلا توسط شخص دیگیری انتخاب شده.'}, primary_key=True, serialize=False, unique=True),
        ),
    ]
