# Generated by Django 5.1 on 2024-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0011_service_specialnews_alter_service_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True, verbose_name='معرفی یولو صفحه درباره ما'),
        ),
    ]
