# Generated by Django 5.1 on 2024-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0012_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='عکس پرسنلی'),
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='تصویر یولو صفحه درباره ما'),
        ),
    ]
