# Generated by Django 5.1 on 2024-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0013_employee_img_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان مقاله')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری')),
                ('writer', models.CharField(max_length=30, verbose_name='نویسنده')),
                ('description', models.TextField(verbose_name='متن مقاله')),
                ('img', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
