# Generated by Django 5.1 on 2024-10-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keyword',
            field=models.CharField(max_length=10, null=True, verbose_name='کلید واژه مقاله'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subject',
            field=models.CharField(max_length=10, null=True, verbose_name='موضوع مقاله در یک کلمه'),
        ),
    ]
