# Generated by Django 5.1 on 2024-10-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0016_alter_blog_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='article',
        ),
    ]
