# Generated by Django 5.1 on 2024-10-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0017_rename_blog_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='wimg',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='تصویر نویسنده مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='photo', verbose_name='تصویر مقاله'),
        ),
    ]
