# Generated by Django 5.1 on 2024-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0018_article_wimg_alter_article_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('call', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('open', models.CharField(max_length=100, verbose_name='روز و ساعات کاری')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=35, verbose_name='عنوان مقاله'),
        ),
    ]
