# Generated by Django 5.1 on 2024-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0019_identity_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('comment', models.TextField(verbose_name='نظر')),
            ],
        ),
    ]
