# Generated by Django 5.1 on 2024-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0020_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری'),
        ),
    ]
