# Generated by Django 5.1 on 2024-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0021_commentblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='num',
            field=models.IntegerField(null=True, verbose_name='شماره مقاله'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='تاریخ بارگذاری'),
        ),
    ]
