# Generated by Django 5.1 on 2024-10-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0024_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
