# Generated by Django 5.1 on 2024-10-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0026_identity_maplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='maplink',
            field=models.CharField(max_length=500, verbose_name='لینک آدرس روی نقشه '),
        ),
    ]
