# Generated by Django 5.1 on 2024-10-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0027_alter_identity_maplink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='maplink',
        ),
    ]
