# Generated by Django 5.1 on 2024-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0028_remove_identity_maplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
