# Generated by Django 5.1 on 2024-11-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0030_identity_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='topservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.CharField(max_length=20, verbose_name='آپشن بالا صفحه اصلی')),
                ('optd', models.CharField(max_length=50, verbose_name='جزئیات آپشن  بالا صفحه اصلی')),
                ('color', models.CharField(max_length=20, verbose_name='لطفا تم رنگی را تغییر ندهید')),
            ],
        ),
    ]
