# Generated by Django 5.1 on 2024-11-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0031_topservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option1detail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option2detail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option3detail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option4detail',
        ),
    ]
