# Generated by Django 5.1 on 2024-11-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0033_shop_prd_date_alter_shop_prd_preprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_prd',
            name='group',
        ),
        migrations.AlterField(
            model_name='shop_prd',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='yolo.category'),
        ),
        migrations.AlterField(
            model_name='shop_prd',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری'),
        ),
        migrations.AlterField(
            model_name='shop_prd',
            name='img',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='shop_prd',
            name='preprice',
            field=models.IntegerField(),
        ),
    ]
