# Generated by Django 5.1 on 2024-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0034_remove_shop_prd_group_alter_shop_prd_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=20, verbose_name='عنوان تبلیغ')),
                ('exp', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('delay', models.CharField(max_length=20, verbose_name='لطفا تاخیر در نمایش را تغییر ندهید')),
                ('img', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
