# Generated by Django 5.1 on 2024-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0036_article_summary_alter_advertisement_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.CharField(max_length=10, verbose_name='کلید واژه مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(max_length=10, verbose_name='موضوع مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='چکیده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='wimg',
            field=models.ImageField(upload_to='photo', verbose_name='تصویر نویسنده مقاله'),
        ),
    ]
