# Generated by Django 5.1 on 2024-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0037_alter_article_keyword_alter_article_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='downservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.CharField(max_length=20, verbose_name='آپشن پایین صفحه اصلی')),
                ('optd', models.CharField(max_length=50, verbose_name='جزئیات آپشن پایین صفحه اصلی')),
                ('img', models.ImageField(upload_to='photo', verbose_name='آیکون')),
            ],
        ),
    ]
