# Generated by Django 5.1 on 2024-11-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0039_remove_downservice_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='downservice',
        ),
    ]
