# Generated by Django 5.1 on 2024-11-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0040_delete_downservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option5detail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option6detail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option7detail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='service',
            name='option8detail',
        ),
    ]
