# Generated by Django 5.1 on 2024-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0041_remove_service_option5_remove_service_option5detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='boldtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان درباره ما'),
        ),
    ]
