# Generated by Django 5.1 on 2024-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0043_employee_theme_alter_service_boldtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='theme',
            field=models.CharField(choices=[('bg-theme-blue', 'blue'), ('bg-theme-yellow', 'yellow'), ('bg-theme-orange', 'orange'), ('bg-theme-pink', 'pink')], default='انتخاب کنید...', max_length=30, null=True, verbose_name='تم رنگی'),
        ),
    ]
