# Generated by Django 5.1 on 2024-11-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0046_rename_gender_faqs_group_alter_faqs_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faqs',
            new_name='fquestion',
        ),
    ]
