# Generated by Django 5.1 on 2024-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0047_rename_faqs_fquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تحویل گیرنده')),
                ('call', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254, null=True)),
                ('city', models.CharField(max_length=20, verbose_name=' استان')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('zip', models.CharField(max_length=20, verbose_name=' کدپستی')),
            ],
        ),
    ]
