# Generated by Django 5.1 on 2024-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0049_article_img1_alter_article_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(null=True, upload_to='photo', verbose_name='بنر 1')),
                ('img2', models.ImageField(null=True, upload_to='photo', verbose_name='بنر 2')),
                ('msg1', models.CharField(max_length=500, verbose_name='توضیحات بنر 1')),
                ('msg2', models.CharField(max_length=100, verbose_name='  خبر مشکی بنر 2')),
                ('msg3', models.CharField(max_length=100, verbose_name='  خبر آبی بنر 2')),
                ('msg4', models.CharField(max_length=500, verbose_name='توضیحات بنر 2')),
            ],
        ),
    ]
