# Generated by Django 5.1 on 2024-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0050_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_prd',
            name='img1',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='تصویر فرعی 1 '),
        ),
        migrations.AddField(
            model_name='shop_prd',
            name='img2',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='تصویر فرعی 2 '),
        ),
        migrations.AddField(
            model_name='shop_prd',
            name='img3',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='تصویر فرعی 3 '),
        ),
        migrations.AlterField(
            model_name='shop_prd',
            name='img',
            field=models.ImageField(upload_to='photo', verbose_name='تصویر اصلی '),
        ),
    ]
