# Generated by Django 5.1 on 2024-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0051_shop_prd_img1_shop_prd_img2_shop_prd_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(help_text='ایمیل معتبر وارد کنید', max_length=254)),
                ('comment', models.TextField(verbose_name='نظر')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ بارگذاری')),
                ('num', models.IntegerField(verbose_name='شماره محصول')),
            ],
        ),
        migrations.AddField(
            model_name='shop_prd',
            name='details',
            field=models.TextField(null=True, verbose_name='شرح کامل محصول'),
        ),
        migrations.AlterField(
            model_name='shop_prd',
            name='description',
            field=models.CharField(max_length=100, verbose_name='شرح مختصر محصول'),
        ),
    ]
