# Generated by Django 5.1 on 2024-11-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0052_product_comment_shop_prd_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_comment',
            new_name='productcomment',
        ),
    ]
