# Generated by Django 5.1 on 2024-11-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0053_rename_product_comment_productcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productcomment',
            new_name='product_comment',
        ),
    ]
