# Generated by Django 5.1 on 2024-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0054_rename_productcomment_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_prd',
            name='preprice',
            field=models.IntegerField(null=True),
        ),
    ]
